name: Publish Docker Images

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # TODO create org secret
          password: ${{ secrets.DOCKER_PASSWORD }} # TODO create org secret
      - name: Pull image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/frc:latest
      - name: Build container # TODO run a script, or use action?
        run: docker build --pull -t ${{ secrets.DOCKER_PASSWORD }}/frc:${{ github.sha }} -t ${{ secrets.DOCKER_PASSWORD }}/frc:latest . --cache-from ${{ secrets.DOCKER_PASSWORD }}/frc:latest
      - name: Publish
        run: docker run -it -e CRATESIO_TOKEN -e TRAVIS_TAG "$DOCKER_USERNAME"/frc:"$TRAVIS_COMMIT" sh -c "cd /first-rust-competition; make ci"
        env:
          CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
          TRAVIS_TAG: ${{ github.sha }}
      - name: Push image with latest tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frc:latest
      - name: Push image with commit hash as tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frc:${{ github.sha }}
